export const CART_ACTIONS = {
    ADD_ITEM_TO_CART: 'cart/ADD_ITEM_TO_CART',
    DELETE_ITEM_FROM_CART: 'cart/DELETE_ITEM_FROM_CART',
    CHANGE_CART_ITEM_QUANTITY: 'cart/CHANGE_CART_ITEM_QUANTITY',
    TOOGLE_CART_OPEN: 'cart/TOOGLE_CART_OPEN'
}